/*
	Copyright 2023 Efabless Corp.

	Author: Mohamed Shalan (mshalan@efabless.com)

	This file is auto-generated by wrapper_gen.py on 2023-11-28

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

	    http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

*/


#ifndef IO_TYPES
#define IO_TYPES
#define   __R     volatile const unsigned int
#define   __W     volatile       unsigned int
#define   __RW    volatile       unsigned int
#endif

#define EF_ACMP_DI_SEL_REG_SELA		0
#define EF_ACMP_DI_SEL_REG_SELA_LEN	1
#define EF_ACMP_DI_SEL_REG_SELB		1
#define EF_ACMP_DI_SEL_REG_SELB_LEN	1
#define EF_ACMP_DI_HI_FLAG	0x1

typedef struct _EF_ACMP_DI_TYPE_ {
	__RW	SEL;
	__R 	reserved[959];
	__W 	icr;
	__R 	ris;
	__RW	im;
	__R 	mis;
} EF_ACMP_DI_TYPE;
